### ISSUE TITLE
Support for unauthenticated API calls is missing

### ISSUE THREAD

**Issue by amsoell** [ying17/rdiolib-php#1]
It's possible I'm missing something, but it doesn't appear that this library allows for making calls to methods that don't require authentication. I specifically tried the `get` method with the following code:

define('RDIO_CLIENT_ID',     'xxx');
define('RDIO_CLIENT_SECRET', 'xxx');
define('RDIO_REDIRECT_URI',  'http://com.com');

```php
require('rdiolib.php');
session_start();
$rdio = new RdioLib(RDIO_CLIENT_ID, RDIO_CLIENT_SECRET, RDIO_REDIRECT_URI);
// Commented out since we shouldn't need authentication
//  $auth = $rdio->authenticate();
echo '<b>$rdio->get()</b>';
print_r($rdio->get(Array("keys"=>"t3370813", "extras"=>"trackNum,bigIcon")));
```

This returns an "Authentication Missing" error message. I'm guessing that there is supposed to be a way to pass the Client ID and Client Secret so Rdio knows they're valid requests, but I don't think this library has a method for this.

**Comment by ying17** [comment]
Will take a look at this, thanks for reporting it.

**Comment by ying17** [comment]
Merged your changes, thanks.

**Comment by amsoell** [comment]
Glad I could help—really appreciate that this library was out there, I almost didn't bother updating my app for OAuth 2 at all. This helped a ton.
